Added linting using ESLint
acquia/next-acms pull request #26
Opened 2022-06-21 17:19 UTC by harumijang

2022-06-21 17:25 UTC, lauriii commented on package.json
> +    "lint": "yarn --cwd starters/basic-starter next lint",
We should update this command so that it runs these newly added rules on CI

2022-06-22 13:32 UTC, lauriii commented on .eslintrc.js
> +module.exports = {
I think we can remove this file since we also have `eslintrc.json`

2022-06-29 12:46 UTC, lauriii requested changes

2022-06-29 19:35 UTC, harumijang commented
I think the `lint` is getting executed now... Below image from running 
`./node_modules/.bin/eslint --cache --ext .ts,.tsx .`
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/35243020/176520430-77bc7762-fd66-43e4-abe9-9f2fd771c430.png">

 However, running `yarn lint` from the root looks like it also runs but then exits fails at the end. I am not sure what the fix should be.
```
next-acms-basic-starter:lint: ERROR: command finished with error: command (starters/basic-starter) yarn run lint exited (1)
command (starters/basic-starter) yarn run lint exited (1)
```

2022-06-30 12:57 UTC, lauriii commented
Did you run `yarn install` in the monorepo before running the command? I get the same error if I try to run `yarn lint` without installing dependencies

2022-07-05 16:14 UTC, harumijang commented
Failing on lint errors because there are many of them

2022-07-05 18:28 UTC, harumijang commented
I'm not sure why it is still throwing a lint error even though I specified that `node` is a `DrupalNode`

<img width="901" alt="image" src="https://user-images.githubusercontent.com/35243020/177391978-820710f6-f5c3-48e4-aa87-dc9896264cbe.png">

2022-07-07 16:23 UTC, merged